[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.venv"]

[phases.install]
cmds = ["python -m venv /opt/venv", "source /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "source /opt/venv/bin/activate && python -m uvicorn application:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11" 