[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn application:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.envs]
PYTHON_VERSION = "3.11" 